import * as pulumi from "@pulumi/pulumi";
import * as github from "@pulumi/github";

const repoName = "Pulumi_created_repo";
const repoDescription = "testing IaC + CICD with pulum";

const repo = new github.Repository(repoName, {
    name: repoName,
    description: repoDescription,
    visibility: "private",
});

const fileName = "README.md"
const readmeContent = `# ${repoName}
This repository was generated by Pulumi to test out Pulumi for IaC + github Actions CICD
`;

const readme = new github.RepositoryFile("README", {
    repository: repo.name,
    file: fileName,
    content: readmeContent,
});


export const repositoryName = repo.name;
export const repositoryUrl = repo.htmlUrl;