name: Pulumi creating repo

on:
  push:
    branches:
      - main

jobs:
  create_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v2

      - name: Applying infrastructure 🚀
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}