name: Pulumi creating repo

on:
  push:
    branches:
      - main

jobs:
  create_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v2

      - name: Pulumi Login
        uses: pulumi/actions@v3
        with:
          command: login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}


      - name: Pulumi Preview
        uses: pulumi/actions@c3
        with:
          command: preview


      - name: Update Infrastructure
        uses: pulumi/actions@v3
        with:
          command: up
          args: --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
